word_list = [
    'spiderman',
    'blackpanther',
    'ironman',
    'gamora',
    'thanos',
    'deadpool',
    'blackwidow',
    'captainamerica',
    'hulk',
    'wolverine',
    'thor',
    'barton',
    'antman',
    'juggernaut',
    'magneto',
    'loki',
    'groot',
    'rogue',
    'starlord',
    'nickfury',
    'mystique',
    'professorx',
    'rocket',
    'drax',
    'cyclops',
    'storm']
    
